development: &psql
  adapter: postgresql
  host: localhost
  database: without_glass
  pool: 5
  timeout: 5000

test:
  <<: *psql
  database: without_glass_test
  pool: 5
  timeout: 5000

production:
  <<: *psql
